In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
#2D Array
a=np.array([[1,3,5,7],[2,4,6,8]])
a

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [ ]:
#3D Array
a=np.array([[[1,3,5,7],[2,4,6,8],[1,2,3,4]]])
a

array([[[1, 3, 5, 7],
        [2, 4, 6, 8],
        [1, 2, 3, 4]]])

In [ ]:
#2D Array FloarType

a=np.array([[1,3,5,7],[2,4,6,8]], dtype=np.float128)
a

array([[1., 3., 5., 7.],
       [2., 4., 6., 8.]], dtype=float128)

**Array Attributes in Numpy**

In [ ]:
a.dtype

dtype('float128')

In [ ]:
a.shape

(2, 4)

In [ ]:
a.size

8

In [ ]:
a.itemsize

16

In [ ]:
a.max()

8.0

In [ ]:
a.min()

1.0

In [ ]:
a.sum()

36.0

In [ ]:
a.std()

2.2912878474779200034

In [ ]:
a.mean()

4.5

In [ ]:
a.var()

5.25

In [ ]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798, 2.64575131],
       [1.41421356, 2.        , 2.44948974, 2.82842712]], dtype=float128)

In [ ]:
x=np.array([1,2,3,4])
y=np.array([2,4,6,8])
x+y

array([ 3,  6,  9, 12])

In [ ]:
a=np.array([1,2,3,4,5,6,7,6,8,9,10])
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
a=np.array([1,2,3,4,5,6,7,6,8,9,10])
a>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
a=np.array([1,2,3,4,5,6,7,6,8,9,10])
a<5

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False])

In [ ]:
a==5

array([False, False, False, False,  True, False, False, False, False,
       False, False])

**Ones ans zeros array**

In [ ]:
one=np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
one=np.ones((2,2,3))
one

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
Zero=np.zeros((2,3))
Zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Zero=np.zeros((4,3))
Zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Zero=np.zeros((2,4,3))
Zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
Zero=np.zeros((1,4,3))
Zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
Zero=np.zeros((3,4,3))
Zero

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

**Ramdomly**

In [ ]:
ran = np.random.random((5,5))
ran

array([[0.34652089, 0.74092122, 0.61817486, 0.52188123, 0.85043648],
       [0.18369697, 0.49761746, 0.25326697, 0.80158974, 0.01401704],
       [0.87648072, 0.21685459, 0.11887207, 0.55715534, 0.9789917 ],
       [0.94736529, 0.32203481, 0.13227184, 0.63847301, 0.79739925],
       [0.83639467, 0.99908856, 0.24210572, 0.91150251, 0.35494038]])

In [ ]:
ran = np.random.random([5,5])
ran

array([[0.13782911, 0.62657905, 0.74957144, 0.33816584, 0.63150656],
       [0.86573245, 0.60376522, 0.03653118, 0.42004179, 0.09787481],
       [0.00922124, 0.76591094, 0.75781607, 0.35952187, 0.06361601],
       [0.05593013, 0.64914421, 0.95729334, 0.62448207, 0.96205982],
       [0.9509259 , 0.6276825 , 0.76510596, 0.18813887, 0.3087276 ]])

In [ ]:
ran = np.random.randint(100,size=(5,5))
ran

array([[ 5, 63, 10,  6, 88],
       [96, 68, 99, 59, 16],
       [15, 90, 11, 46, 17],
       [72, 66, 13, 97, 42],
       [14,  1, 40, 60, 87]])

In [ ]:
ran = np.random.randint(20,30,(5,5))
ran

array([[27, 29, 24, 25, 23],
       [21, 23, 22, 24, 20],
       [20, 29, 21, 24, 29],
       [29, 29, 24, 22, 26],
       [20, 21, 28, 23, 21]])

**Reshape array shape**

In [ ]:
a=np.array([[[1,3,5,7],[2,4,6,8],[1,2,3,4]]])

a=a.reshape(3,4)
a

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [1, 2, 3, 4]])

In [ ]:

a=a.reshape(2,6)
a

array([[1, 3, 5, 7, 2, 4],
       [6, 8, 1, 2, 3, 4]])

In [ ]:
a=a.reshape(4,3)
a


array([[1, 3, 5],
       [7, 2, 4],
       [6, 8, 1],
       [2, 3, 4]])

In [ ]:
a=a.reshape(6,2)
a

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8],
       [1, 2],
       [3, 4]])

**Array Slicing**

In [ ]:
a=np.array([[27, 29, 24, 25, 23],
       [21, 23, 22, 24, 20],
       [20, 29, 21, 24, 29],
       [29, 29, 24, 22, 26],
       [20, 21, 28, 23, 21]])
a
a[(0,3),(0,3)]


array([27, 22])

In [ ]:
import pandas as pd


**Dataframe Create**

In [ ]:
df2=pd.DataFrame(np.array([[1,2,3],[4,5,6],[2,3,4]]))
df2


0  1  2
0  1  2  3
1  4  5  6
2  2  3  4

In [ ]:
df2.shape

(3, 3)

In [ ]:
df2.describe()

0         1         2
count  3.000000  3.000000  3.000000
mean   2.333333  3.333333  4.333333
std    1.527525  1.527525  1.527525
min    1.000000  2.000000  3.000000
25%    1.500000  2.500000  3.500000
50%    2.000000  3.000000  4.000000
75%    3.000000  4.000000  5.000000
max    4.000000  5.000000  6.000000

In [ ]:
df2.corr()

0    1    2
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0

In [ ]:
df2[0] #coloumn access

0    1
1    4
2    2
Name: 0, dtype: int64

In [ ]:
df2[[0,1,2]] #multiple coloumn access

0  1  2
0  1  2  3
1  4  5  6
2  2  3  4

In [ ]:
#Row Access

In [ ]:
df2.loc[0]

0    1
1    2
2    3
Name: 0, dtype: int64

In [ ]:
df2.loc[2]

0    2
1    3
2    4
Name: 2, dtype: int64

In [ ]:
df=pd.DataFrame(np.array([[1,2,3],[4,5,6],[7,8,9]]))
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df.loc[[0,2]] #Row access

0  1  2
0  1  2  3
2  7  8  9

In [ ]:
df[[0,2]] # coloumn access

0  2
0  1  3
1  4  6
2  7  9

In [ ]:
df.iloc[0,:]

0    1
1    2
2    3
Name: 0, dtype: int64

In [ ]:
df.iloc()

In [ ]:
df.isnull()

0      1      2
0  False  False  False
1  False  False  False
2  False  False  False

In [ ]:
df1=pd.DataFrame(np.array([[1,None,3],[4,5,6],[7,None,9]]))
df1

0     1  2
0  1  None  3
1  4     5  6
2  7  None  9

**Null Value Handle**

In [ ]:
df1.isnull()

0      1      2
0  False   True  False
1  False  False  False
2  False   True  False

In [ ]:
df1.isnull().sum()

0    0
1    2
2    0
dtype: int64

In [ ]:
df1.dropna()


0  1  2
1  4  5  6

In [ ]:
df1

0     1  2
0  1  None  3
1  4     5  6
2  7  None  9

In [ ]:
df1=df1.dropna()

In [ ]:
df1

0  1  2
1  4  5  6

In [ ]:
df1=pd.DataFrame(np.array([[1,None,3],[4,5,6],[7,None,9]]))
df1

0     1  2
0  1  None  3
1  4     5  6
2  7  None  9

In [ ]:
df1.fillna("10")

0   1  2
0  1  10  3
1  4   5  6
2  7  10  9

In [ ]:
df1.fillna("ND")

0   1  2
0  1  ND  3
1  4   5  6
2  7  ND  9

In [ ]:
df1.fillna(df.mean())

0    1  2
0  1  5.0  3
1  4  5.0  6
2  7  5.0  9

**Dataset load from Xcell**

In [ ]:
##pk = pd.read_csv('/conect/pokemon_data.csv') ## for csv file
import pandas as pd

In [ ]:
pk=pd.read_excel('/pokemon_data.xlsx')   # for xcell dataset

In [ ]:
pk.head()


#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire      ND  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

In [ ]:
pk.tail()

#                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
795  719              Diancie     Rock  Fairy  50     100      150      100   
796  719  DiancieMega Diancie     Rock  Fairy  50     160      110      160   
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150   
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170   
799  721            Volcanion     Fire  Water  80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
795      150     50           6       True  
796      110    110           6       True  
797      130     70           6       True  
798      130     80           6       True  
799       90     70           6       True

In [ ]:
pk.isnull()

#   Name  Type 1  Type 2     HP  Attack  Defense  Sp. Atk  Sp. Def  \
0    False  False   False   False  False   False    False    False    False   
1    False  False   False   False  False   False    False    False    False   
2    False  False   False   False  False   False    False    False    False   
3    False  False   False   False  False   False    False    False    False   
4    False  False   False    True  False   False    False    False    False   
..     ...    ...     ...     ...    ...     ...      ...      ...      ...   
795  False  False   False   False  False   False    False    False    False   
796  False  False   False   False  False   False    False    False    False   
797  False  False   False   False  False   False    False    False    False   
798  False  False   False   False  False   False    False    False    False   
799  False  False   False   False  False   False    False    False    False   

     Speed  Generation  Legendary  
0    False       False      False  
1    False       False      False  
2    False       False      False  
3    False       False      False  
4    False       False      False  
..     ...         ...        ...  
795  False       False      False  
796  False       False      False  
797  False       False      False  
798  False       False      False  
799  False       False      False  

[800 rows x 12 columns]

In [ ]:
pk.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
pk=pk.fillna("ND")
pk

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire      ND  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]